---
title: "DC Bikesharing Analysis"
author: "Seth Taylor"
date: "September 15, 2018"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "figs/", dev = c('png'))
```

##Introduction


```{r Data}
bikes <- read.csv("C:/Users/Seth.Taylor/Documents/Github/Kaggle---DC-City-Bikesharing/Data/hour.csv")
```

##Data Cleaning

```{r Data_Shape}
#Looking at shape of data and checking that there's no missing data
head(bikes)

str(bikes)

all(complete.cases(bikes))
```

```{r Convert_Variables}
#Convert categorical variables to factor
factors <- c("season", "yr", "mnth", "hr", "holiday", "weekday", "workingday", "weathersit")
bikes[factors] <- lapply(bikes[factors], as.factor)
```

##EDA

```{r Summary}
summary(bikes)
```

```{r Mean Bike Usage Per Day by Type}
library(ggplot2)
ggplot(bikes, aes(dteday)) + stat_summary(aes(y = casual, group = 1, color = "casual"), fun.y = mean, geom = "line") + stat_summary(aes(y = registered, group = 1, color = "registered"), fun.y = mean, geom = "line") + theme(axis.text.x = element_blank())
```

```{r Count_per_Month}
boxplot(cnt~mnth, data = bikes)
```

```{r Count_by_Season}
boxplot(cnt~season, data = bikes)
```

```{r Count_by_Weekday}
boxplot(cnt~weekday, data = bikes)
```

```{r Count_by_Workingday}
boxplot(cnt~workingday, data = bikes)
```

```{r Count_by_Holiday}
boxplot(cnt~holiday, bikes)
```

```{r Count_by_Hours}
boxplot(cnt ~ hr, data = bikes)
```


```{r Linear_Model}
#Creating linear model to identify statistically signficant factors influencing count of bikes
fit <- lm(cnt ~ season + hr + holiday + workingday + atemp + hum + windspeed + weathersit, data = bikes)

summary(fit)
```
